# Archivo de configuraci칩n para el generador de localizaci칩n

# El archivo .arb base
template-arb-file: app_en.arb

# El archivo .dart que se generar치
output-localization-file: app_localizations.dart

# Opcional: El nombre de la clase que se generar치
output-class: AppLocalizations